### ISSUE TITLE
Handling of "large" resources

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#140]
@gvidon I've had reports that "large" resources (eg: 3mb) cause the app to crash. Can you please check where the bottleneck is here, as this affects OpenSpending as well. 

Here is an example 3mb file that leads to errors: https://raw.githubusercontent.com/rgrp/dataset-gla/master/data/all.csv

**Comment by gvidon** [comment]
@pwalsh ok, no problem.

**Comment by gvidon** [comment]
@pwalsh tried to load this file two times. It didn't actually crash the app (at least in Chrome), but took incredibly long time to do computations in json table schema infer method — https://github.com/okfn/jsontableschema-js/blob/master/infer.js#L56 And it blocks browser window. 

Excluding this https://github.com/okfn/jsontableschema-js/blob/master/infer.js#L76 didn't help. So the problem is in that huge loop which goes through the whole CSV data array.

Possible solution would be showing loading screen with no animation when uploading CSV, as animation will probably be blocked and confuse users.

More complicated solution would be using advanced computation methods, like html5 workers or something like this.

**Comment by gvidon** [comment]
@alexeyk for now, please add loading state when uploading CSV. It should overlap the whole page and place ```Loading...``` in absolute center of the page.

**Comment by gvidon** [comment]
@alexeyk no animation gif or anything like this should be used.

**Comment by pwalsh** [comment]
@gvidon you've dealt with this now elsewhere, right? We need to fix it here.

**Comment by pwalsh** [comment]
Another example file that freezes the app:

example data source (.csv file) that I attempted to upload and app froze? http://opendata.cambridgeshireinsight.org.uk/dataset/area-classification-cambridgeshire-output-areas/resource/0a3d1376-c451-44c8-aa64
